version: "2"
run:
  timeout: 5m

linters:
  default: all
  disable:
    - depguard
    - wsl
    - wrapcheck
    - mnd
  settings:
    exhaustruct:
      exclude:
        - 'github\.com/spf13/cobra\.Command'
        - 'github\.com/rs/zerolog\.ConsoleWriter'
        - 'gopkg\.in/natefinch/lumberjack\.v2\.Logger'
        - 'net/url\.URL'
    lll:
      line-length: 160
    varnamelen:
      ignore-names:
        - v
        - u
        - ok
        - i
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - linters:
          - revive
        text: 'avoid package names that conflict with Go standard library package names'

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
