version: "2"
run:
  timeout: 5m

linters:
  default: all
  disable:
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
